In [1]:
#importing the needed packages
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA

In [2]:
#loading the dataset
data=pd.DataFrame(pd.read_csv("AAPL.csv"))

data.head()

Date      Open      High       Low     Close  Adj Close     Volume
0  1980-12-12  0.128348  0.128906  0.128348  0.128348   0.100600  469033600
1  1980-12-15  0.122210  0.122210  0.121652  0.121652   0.095352  175884800
2  1980-12-16  0.113281  0.113281  0.112723  0.112723   0.088353  105728000
3  1980-12-17  0.115513  0.116071  0.115513  0.115513   0.090540   86441600
4  1980-12-18  0.118862  0.119420  0.118862  0.118862   0.093165   73449600

In [3]:
#dimensions of the dataset
data.shape

(10272, 7)

In [4]:
#checking whether there is any null values
data.isnull().sum()

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [5]:
#droping the data column 

data.drop(['Date'],axis=1,inplace=True)

In [6]:
#dimesions after droping
data.shape

(10272, 6)

In [7]:
#x and y 
Y=data.pop('Volume')

X=data

In [8]:
#train test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y,train_size=0.7, test_size=0.3, random_state=0)

In [9]:
#performing normal mr
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [10]:
#predicting the result
print("PREDICTION:")
pred = model.predict(X_test)
pred

PREDICTION:


array([3.41737811e+08, 3.42006359e+08, 1.16146020e+08, ...,
       3.38565927e+08, 4.09877597e+08, 3.41059573e+08])

In [11]:
y_test
#y_test.shape--->3082

4709    362443200
2443    156116800
9880    100566000
8755    224917200
7940    556995600
          ...    
8182    443038400
2481     99489600
1045    492441600
8555    187769600
3170    353617600
Name: Volume, Length: 3082, dtype: int64

In [12]:
#OBSERVATION 1

In [13]:
#score
print("SCORE FOR THE MODEL")
np.round(model.score(X_test,y_test),4)

SCORE FOR THE MODEL


0.0728

In [14]:
#error
print("RMSE FOR THE MODEL")
from sklearn.metrics import mean_squared_error
np.round(mean_squared_error(y_test,pred,squared=False),4)

RMSE FOR THE MODEL


314882094.0106

In [15]:
#mse
print("MSE FOR THE MODEL")
from sklearn.metrics import mean_squared_error
np.round(mean_squared_error(y_test,pred),4)

MSE FOR THE MODEL


9.915073312848011e+16

In [16]:
#mae
print("MAE FOR THE MODEL")
from sklearn.metrics import mean_absolute_error
np.round(mean_absolute_error(y_test,pred),4)

MAE FOR THE MODEL


215982730.1536

In [17]:
#intercept
print("INTERCEPT VALUE:")
model.intercept_

INTERCEPT VALUE:


337043378.1082199

In [18]:
#coefficients 
print("COEFFICIENT VALUES :")
model.coef_

COEFFICIENT VALUES :


array([ 2.55209195e+06,  1.31838933e+08, -1.31238882e+08,  5.92590740e+07,
       -6.85798121e+07])

In [19]:
#regularization :ridge
from sklearn.linear_model import Ridge
model1 = Ridge(alpha=0.70)
model1.fit(X_train,y_train)

Ridge(alpha=0.7)

In [20]:
#predicting coefficents
print("PREDICTION USING RIDGE REGRESSION WHEN ALPHA=0.70")
pred1 = model1.predict(X_test)
pred1

PREDICTION USING RIDGE REGRESSION WHEN ALPHA=0.70


array([3.41747023e+08, 3.42013575e+08, 1.16222270e+08, ...,
       3.38577432e+08, 4.09824793e+08, 3.41067705e+08])

In [ ]:
#OBSERVATION 2

In [21]:
#score
print("SCORE USING RIDGE REGRESSION WHEN ALPHA=0.70")
np.round(model1.score(X_test,y_test),4)

SCORE USING RIDGE REGRESSION WHEN ALPHA=0.70


0.0728

In [22]:
#error
print("RMSE USING RIDGE REGRESSION WHEN ALPHA=0.70")
np.round(mean_squared_error(y_test,pred1,squared = False),4)

RMSE USING RIDGE REGRESSION WHEN ALPHA=0.70


314883364.7323

In [23]:
#mse
print("MSE USING RIDGE REGRESSION WHEN ALPHA=0.70")
np.round(mean_squared_error(y_test,pred1),4)

MSE USING RIDGE REGRESSION WHEN ALPHA=0.70


9.915153338515203e+16

In [24]:
#mae
print("MAE USING RIDGE REGRESSION WHEN ALPHA=0.70")
np.round(mean_absolute_error(y_test,pred1),4)

MAE USING RIDGE REGRESSION WHEN ALPHA=0.70


215984406.4279

In [25]:
model2 = Ridge()

In [26]:
#negative mae
from sklearn.model_selection import GridSearchCV
from numpy import arange
grid = dict()
grid['alpha'] = arange(0, 1, 0.01)
# define search
search = GridSearchCV(model2, grid, scoring='neg_mean_absolute_error', n_jobs=-1)
results = search.fit(X_train, y_train)

In [27]:
results

GridSearchCV(estimator=Ridge(), n_jobs=-1,
             param_grid={'alpha': array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])},
             scoring='neg_mean_absolute_error')

In [28]:
print("RESULTS OF RIDGE REGRESSION FOR BEST FIT ALPHA")
print('MAE: %.3f' % results.best_score_)
print('Config: %s' % results.best_params_)

RESULTS OF RIDGE REGRESSION FOR BEST FIT ALPHA
MAE: -219163389.293
Config: {'alpha': 0.99}


In [29]:
pred3 = search.predict(X_test)

In [30]:
#error
print("PREDICTION USING RIDGE REGRESSION FOR BEST FIT ALPHA")
np.round(mean_squared_error(y_test,pred3,squared = False),4)

PREDICTION USING RIDGE REGRESSION FOR BEST FIT ALPHA


314883895.3101

In [31]:
#score
print("SCORE USING RIDGE REGRESSION FOR BEST FIT ALPHA")
np.round(search.score(X_test,y_test),4)

SCORE USING RIDGE REGRESSION FOR BEST FIT ALPHA


-215985097.8629

In [32]:
#error
print("RMSE USING RIDGE REGRESSION FOR BEST FIT ALPHA")
np.round(mean_squared_error(y_test,pred3,squared = False),4)

RMSE USING RIDGE REGRESSION FOR BEST FIT ALPHA


314883895.3101

In [33]:
#mse
print("MSE USING RIDGE REGRESSION FOR BEST FIT ALPHA")
np.round(mean_squared_error(y_test,pred3),4)

MSE USING RIDGE REGRESSION FOR BEST FIT ALPHA


9.915186752564126e+16

In [34]:
#mae
print("MAE USING RIDGE REGRESSION FOR BEST FIT ALPHA")
np.round(mean_absolute_error(y_test,pred3),4)

MAE USING RIDGE REGRESSION FOR BEST FIT ALPHA


215985097.8629

In [35]:
# implementation of Principal Compoenet Analysis (PCA)
from sklearn.decomposition import PCA
pca = PCA(n_components=5)
df = pca.fit_transform(X)
data1 = pd.DataFrame(data = df,columns = ['RESULT1','RESULT2','RESULT3','RESULT4','RESULT5'])
data1.head()

RESULT1   RESULT2   RESULT3   RESULT4   RESULT5
0 -26.315245  0.369068  0.036820 -0.029753  0.003123
1 -26.329326  0.370116  0.037327 -0.029924  0.002855
2 -26.348436  0.371740  0.037549 -0.029950  0.002877
3 -26.342715  0.371402  0.037139 -0.029789  0.003154
4 -26.335547  0.370793  0.037055 -0.029780  0.003146

In [36]:
data1.shape

(10272, 5)

In [37]:
print("VARIANCE RATIO USING PCA")
pca.explained_variance_ratio_

VARIANCE RATIO USING PCA


array([9.99784867e-01, 1.65821998e-04, 2.63682405e-05, 1.89414078e-05,
       4.00101895e-06])

In [38]:
print(" PCA COMPONENTS")
pca.components_

 PCA COMPONENTS


array([[ 0.44822324,  0.45318366,  0.44327278,  0.44846134,  0.44284554],
       [-0.30450887, -0.20395535, -0.24702401, -0.12283294,  0.88857626],
       [ 0.61079374,  0.29632947, -0.37422916, -0.62573043,  0.0867975 ],
       [-0.27283837,  0.59474421, -0.64340931,  0.38874119, -0.08211762],
       [-0.50878335,  0.55811733,  0.434126  , -0.49105621,  0.0065539 ]])

In [39]:
model3 = LinearRegression()

In [40]:
X_train1,X_test1,y_train1,y_test1 = train_test_split(data1, Y, test_size=0.20, random_state=0)

In [41]:
model3.fit(X_train1,y_train1)

LinearRegression()

In [42]:
print("PREDICTION USING PCA")
pred4 = model3.predict(X_test1)
pred4

PREDICTION USING PCA


array([3.38306180e+08, 3.38735844e+08, 1.15682635e+08, ...,
       3.37443125e+08, 3.39917961e+08, 4.02179191e+08])

In [43]:
y_test1

4709     362443200
2443     156116800
9880     100566000
8755     224917200
7940     556995600
           ...    
7542     508348400
5607     195098400
1594     539840000
6032     928625600
6935    1888392800
Name: Volume, Length: 2055, dtype: int64

In [ ]:
#OBSERVATION 3

In [58]:
print("SCORE USING PCA")
np.round(search.score(X_test1,y_test1),5)

SCORE USING PCA


-269616798.23646

In [46]:
print("RMSE USING PCA")
np.round(mean_squared_error(y_test1,pred4,squared = False),4)

RMSE USING PCA


323548349.6516

In [47]:
print("MSE USING PCA")
np.round(mean_squared_error(y_test,pred3),3)

MSE USING PCA


9.915186752564126e+16

In [48]:
print("MAE USING PCA")
np.round(mean_absolute_error(y_test,pred3),4)

MAE USING PCA


215985097.8629

In [49]:
from sklearn.model_selection import GridSearchCV
from numpy import arange
grid = dict()
grid['alpha'] = arange(0, 1, 0.01)
# define search
search1 = GridSearchCV(model2, grid, scoring='neg_mean_absolute_error', n_jobs=-1)
results1 = search1.fit(X, Y)

In [50]:
print("RESULTS FOR BEST FIT ALPHA USING PCA")
print('MAE: %.3f' % results1.best_score_)
print('Config: %s' % results1.best_params_)

RESULTS FOR BEST FIT ALPHA USING PCA
MAE: -670979141.100
Config: {'alpha': 0.99}


In [51]:
pred5 = search1.predict(X_test)

In [52]:
print("SCORE FOR BEST FIT ALPHA USING PCA")
np.round(model3.score(X_test1,y_test1),4)

SCORE FOR BEST FIT ALPHA USING PCA


0.0709

In [53]:
print("RMSE FOR BEST FIT ALPHA USING PCA")
np.round(mean_squared_error(y_test,pred5,squared = False),4)

RMSE FOR BEST FIT ALPHA USING PCA


314748141.7113

In [54]:
print("MSE FOR BEST FIT ALPHA USING PCA")
np.round(mean_squared_error(y_test,pred5),4)

MSE FOR BEST FIT ALPHA USING PCA


9.906639271070944e+16

In [55]:
print("MAE FOR BEST FIT ALPHA USING PCA")
np.round(mean_absolute_error(y_test,pred5),4)

MAE FOR BEST FIT ALPHA USING PCA


215088154.0796

In [ ]:
#from this what we can interpret is that result is same
#when performing pca,regularization and noraml mr for the choosen dataset